[image storage="a1" page=fore layer=base]
[playse storage="decide2"]
@title name="由佳ちゃんの告白!?"
[rclick enabled=false]
[laycount layers=3]
[position layer=message0 frame="" opacity=0 top=260 left=6 width=400 height=250]
[font size=28]
　　　 ☆操作説明☆
[move layer=message0 time=200 path="(6,100,255)"]
[wait time=1000]
[move layer=message0 time=200 path="(6,-50,255)"]
[wm]
[layopt page=fore visible=true layer=0]
[image storage="help1" page=fore layer=0 opacity=0]
[move layer=0 time=500 path="(0,0,255)"][wm]
[image storage="help1" page=fore layer=base]
[image storage="yuka1" page=fore layer=0 left=-200 top=2]
[move layer=0 time=400 path="(250,2,255)"]
[wm]
[image storage="help2" page=fore layer=1 opacity=0 left=50]
[layopt page=fore visible=true layer=1]
[move layer=1 time=1000 path="(0,0,255)"]
[wm]
[position layer=message0 vertical=true page=fore top=15 left=5 width=240 height=260]
[font face="ＭＳ ゴシック" edge=true size=14]
[style linespacing=12]
はぁい、前作コスモカオスの[r]
ヒロイン由佳で～すッ！[r]
関係ないところで登場です。[r]
テンション上げてくよ～！[r][l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
まず、このソフトについて！[r]
タイトルは…ええと、[r]
『紫陽花しようか！』だよ。[r]
変なタイトルだね。[r]
今のところver.1.13です。[r]
更新されたら、連絡します！[l]
[cm][font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[image layer=2 page=fore storage="yuka2" left=296 top=72]
[layopt layer=2 visible=true]
ちなみにこのヘルプだけど、[r]
適当です。意味ありません。[r]
多分気づかれないと思うほどの[r]
適当な機能です。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[layopt layer=2 visible=false]
誰も見てない、ってことは、[r]
ここで私が愛の告白をしても[r]
全然問題ないってことだよね！[r]
わーい、わーい♪[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
えっと、閑話休題。[r]
というか、本題を始めます。[r]
ここでは、知っておくと[r]
ちょっとお得な気分になれる[r]
操作方法を説明するね。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
まず、上のメニューバーの[r]
「既読スキップ」機能！[r]
読んだことのあるイベントは、[r]
この「既読スキップ」の文字が[r]
黒くなるからね。[r]
まだ読んだことないシーンだと、[r]
灰色のままです。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
「既読スキップ」は[r]
既読しかスキップできません。[r]
もし、未読部分もスキップしたい、[r]
なーんてせっかちさんがいたら、[r]
キーボードの「Enter」キーを[r]
押しっぱなしにしてみよう。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[layopt layer=2 visible=true]
「Enter」キーを押しっぱなし[r]
にすれば、あっという間に[r]
次の選択肢まで一っ飛びー。[r]
だけど、あまり未読スキップは[r]
しないで欲しいけどね。[r]
既読スキップだけで[r]
十分行けると思うよ、多分。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[layopt layer=2 visible=false]
次に、「メッセージ履歴」機能！[r]
これもメニューバーにあるけど、[r]
実は、マウスのホールドを[r]
ちょいちょいと上に回転させると。[r]
メッセージの履歴が見れちゃう！[r]
これは結構便利な機能だから、[r]
読み飛ばしちゃったなーって時は、[r]
ホールドをクリクリ回してね。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
最後に、「ロード」！[r]
このゲームは、ちょっと不親切で、[r]
どこでもセーブはできないのだ。[r]
だけど、ロードはどこでもできる。[r]
右クリック押して！[r]
ロード画面が開くから！[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
ちょっとしたコツになるけど、[r]
こまめにセーブをして、[r]
失敗したらロードでやり直す。[r]
それがクリアへの近道です。[r]
ロードを最大限に利用してね。[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[layopt layer=2 visible=true]
では、おさらいでーす。[r]
既読スキップはメニューバー。[r]
未読スキップはEnter押しっぱ。[r]
履歴はホールドくりくり。[r]
ロードは右クリック。[r]
この４点を上手く使って、[r]
快適にゲームをしてください！[l]
[cm]
[font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[layopt layer=2 visible=false]
もしバグや感想があったり、[r]
攻略方法が必要だったら、[r][font shadow=false color=0x0000FF edge=false]
[link enterse=sentaku1 exp="System.shellExecute('http://www.eonet.ne.jp/~shime/')" hint="「シャイムの私目」を開きます"]伽那ノ光のサイト[endlink]
[font shadow=true color="default" edge=true][r]
を参考にしてね。[r]
掲示板で質問したり、[r]
攻略サイトで情報集めたり、[r]
できるはずだから……。[l]
[cm][font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
詳しいことは、[r]
readme.txtに[r]
書いてあるかもね。[r]
書いてないかもだけど。[r]
この辺りは、前作の[r]
コスモカオスと同じですー。[l]
[cm][font face="ＭＳ ゴシック" edge=true size=14][style linespacing=12]
[layopt layer=2 visible=true]
こんなところかな。[r]
このヘルプの終了は、[r]
このウィンドウの[r]
右上の×印を[r]
押してくれたらいいよ。[r]
以上お助け(？)[r]
由佳ちゃんでした～！
[s]